language: node_js
node_js:
    - "10"

services: 
    - docker

env:
    global:
        - COMMIT=${TRAVIS_COMMIT::6}
        - IMAGE=an19940611/vuex-ssr

before_install:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin;
    - docker login --username=_ --password=$(heroku auth:token) registry.heroku.com

install: 
    - npm install
    - npm install -g heroku

script: 
    - docker version
    - docker-compose version
    - yarn build
    - docker build -t $IMAGE:$COMMIT . --no-cache

deploy:
    provider: script
    script: 
        docker push $IMAGE;
        heroku container:release web --app $HEROKU_APP;
        docker logout;
    branch: master